name: QA

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Sandbox Cypress Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start sandbox environment using docker-compose
        run: make docker-compose-up-local

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14.5.0'

      - name: Install dependencies
        run: make install

      - name: Run cypress tests
        run: make cypress-run

      - name: Upload html reports
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-html-report
          path: ./qa/results/mochawesome/html/combined-report-mocha.html

      - name: Comment in PR with cypress report
        uses: thollander/actions-comment-pull-request@v2
        if: always()
        with:
          message: |
            ## Cypress Report
            QA job has finished with status **${{ job.status }}**.