name: QA

on:
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    name: Sandbox Cypress Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start sandbox environment using docker-compose
        run: make docker-compose-up-local

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '14.5.0'

      - name: Install dependencies
        run: make install

      - name: Run cypress tests
        working-directory: ./qa
        run: npx cypress run --record --key ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Generate reports
        working-directory: ./qa
        if: always()
        run: npm run reports 

      - name: Upload html report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-html-report
          path: ./qa/results/mochawesome/html/

      - name: Publish cypress junit report
        uses: mikepenz/action-junit-report@v3
        if: always()
        with:
          report_paths: 'qa/combined-report-junit.xml'